### ISSUE TITLE
Problem with update of attributes

### ISSUE THREAD

**Issue by skeptikos** [nativelogix/xquerrail2.framework#121]
There is a problems with updates of attributes, which I noticed when using a `type="update-timestamp"` attribute.  

Here is a JSON-converted snippet with both attribute and element timestamp fields. Notice only the element is updated:
```xquery
  "tracked": [
    {
      "_id": "n89b85a20c209b964",
      "_dateCreated": "2015-09-16T14:24:36.862914-04:00",
      "_dateModified": "2015-09-16T14:24:36.862914-04:00",
      "update-timestamp": "2015-09-16T14:25:18.657561-04:00",
      "create-timestamp": "2015-09-16T14:24:36.862914-04:00",
    }
```

I believe I have tracked down the problem in `base-model:build-attribute()`:
```xquery
  let $value := model:build-value($context, $update-value, $current-value)
  return
    if(fn:exists($update-value)) then
      attribute {$qname} {
        $value
      }
    else if($partial and fn:exists($current)) then
      attribute {$qname} {
        $current-value
      }
    else if(fn:exists($value)) then
      attribute {$qname} {
        $value
      }
    else if(fn:empty($current) and fn:exists($default-value)) then
      attribute {$qname} {
        $default-value
      }
```
The 1st  `if(...)` clause builds using $value, but it incorrectly tests $update-value. This means it fails on constructed values unless there is a corresponding user-supplied one. The 3rd clause would be correct it follows the 2nd clause testing for `$current` when `$partial` is on, which will override it. 

To fix the 1st clause should be changed to test `$value` and the 3rd clause is then identical, redundant, and useless, and so should be deleted:
```xquery
  let $value := model:build-value($context, $update-value, $current-value)
  return
    if(fn:exists($value)) then
      attribute {$qname} {
        $value
      }
    else if($partial and fn:exists($current)) then
      attribute {$qname} {
        $current-value
      }
    else if(fn:empty($current) and fn:exists($default-value)) then
      attribute {$qname} {
        $default-value
      }
```
I've tested locally and seems to function as expected.

**Comment by rlouapre** [comment]
The fix will be available in the next release (due by end of this week)
