### ISSUE TITLE
model:recursive-build should not require update transaction mode

### ISSUE THREAD

**Issue by rlouapre** [nativelogix/xquerrail2.framework#80]
@garyvidal 
Why does xquerrail need to invoke xdmp:document-delete from model:build-binary?  
https://github.com/nativelogix/xquerrail2.framework/blob/master/src/main/_framework/base/base-model.xqy#L1212

**Comment by garyvidal** [comment]
My recommendation is to push uri into $binary-dependencies and clean up in the update method.  This will thwart query mode requirement when using recursive build

Ex> 
declare variable $binary-deletes := map:map()

...
 if($fileURI ne $current/text())
             then  map:put($binary-deletes, $current/text(),"1")
             else  (),
...
in update
for $key in map:keys($binary-deletes) ! xdmp:document-delete(.)
